### ISSUE TITLE
error: Uncaught (in promise) ConnectionReset: Socket has already been closed

### ISSUE THREAD

**Issue by asciidude** [pxpcandy/agda.js#1]
```bash
error: Uncaught (in promise) ConnectionReset: Socket has already been closed
          new Deno.errors.ConnectionReset("Socket has already been closed"),
          ^
    at https://deno.land/std@0.65.0/ws/mod.ts:386:11
    at Array.forEach (<anonymous>)
    at WebSocketImpl.ensureSocketClosed (https://deno.land/std@0.65.0/ws/mod.ts:384:12)
    at WebSocketImpl.close (https://deno.land/std@0.65.0/ws/mod.ts:366:12)
    at async WebSocketImpl.[Symbol.asyncIterator] (https://deno.land/std@0.65.0/ws/mod.ts:268:11)
    at async WebSocket.open (https://deno.land/x/websocket@v0.0.6/lib/websocket.ts:80:24)
```

**Comment by pxpcandy** [comment]
Issue solved

**Comment by asciidude** [comment]
Solved
